CREATE TABLE files (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(500) NOT NULL,
    original_name VARCHAR(500) NOT NULL,
    mime_type   VARCHAR(100),
    size_bytes  BIGINT NOT NULL,
    storage_url TEXT NOT NULL,
    storage_type VARCHAR(20) NOT NULL DEFAULT 'LOCAL',
    uploaded_by BIGINT REFERENCES users(id),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_files_uploaded_by ON files(uploaded_by);
