# ---- Dev: H2 in-memory ----
spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:template_db;MULTI_STATEMENT=FALSE}
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driver-class-name=${DATABASE_DRIVER:org.h2.Driver}

app.datasource.secondary.url=${SECONDARY_DATABASE_URL:jdbc:h2:mem:secondary_db;MULTI_STATEMENT=FALSE}
app.datasource.secondary.username=${SECONDARY_DATABASE_USERNAME:sa}
app.datasource.secondary.password=${SECONDARY_DATABASE_PASSWORD:}
app.datasource.secondary.driver-class-name=${SECONDARY_DATABASE_DRIVER:org.h2.Driver}

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}

logging.level.root=${LOG_LEVEL_ROOT:INFO}
logging.level.com.sepring.template=${LOG_LEVEL_APP:DEBUG}

# H2 Console (dev only)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
