# ---- Prod: PostgreSQL ----
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=${DATABASE_DRIVER:org.postgresql.Driver}

app.datasource.secondary.url=${SECONDARY_DATABASE_URL}
app.datasource.secondary.username=${SECONDARY_DATABASE_USERNAME}
app.datasource.secondary.password=${SECONDARY_DATABASE_PASSWORD}
app.datasource.secondary.driver-class-name=${SECONDARY_DATABASE_DRIVER:org.postgresql.Driver}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

logging.level.root=${LOG_LEVEL_ROOT:WARN}
logging.level.com.sepring.template=${LOG_LEVEL_APP:INFO}
