spring.application.name=${APP_NAME:template}
server.port=${SERVER_PORT:8080}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# ---- Primary Datasource ----
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=${DATABASE_DRIVER}

# ---- Secondary Datasource ----
app.datasource.secondary.url=${SECONDARY_DATABASE_URL}
app.datasource.secondary.username=${SECONDARY_DATABASE_USERNAME}
app.datasource.secondary.password=${SECONDARY_DATABASE_PASSWORD}
app.datasource.secondary.driver-class-name=${SECONDARY_DATABASE_DRIVER}

# ---- JPA / Hibernate ----
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# ---- Swagger / OpenAPI ----
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=method

# ---- JWT ----
app.jwt.secret=${JWT_SECRET:8BnlLtbjl/FhbMGpF+duOoIlskRlujEMSa952uGhAdY=}
app.jwt.expiration=${JWT_EXPIRATION:86400000}

# ---- AES-CBC ----
app.aes-cbc.key=${AES_KEY_B64:ccooqIkjqKNSGgtWARM9iN54152lG/En44az0q8wSjo=}

# ---- Logging ----
logging.level.root=${LOG_LEVEL_ROOT:INFO}
logging.level.com.sepring.template=${LOG_LEVEL_APP:DEBUG}
